apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.server.tolerations | indent 8 }}
      containers:
        - name: argocd-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
