replicaCount: 1

image:
  repository: dattruongquoc/app
  tag: 67d0b0fc7cc6ed9c1e50170f1dc0c6ade9b9419d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx

  hosts:
    - host: ""   # hoặc "*" để wildcard
      paths:
        - path: /app
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  namespace: api

tolerations:
  - key: "namespace"
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"
#change triger helm release