replicaCount: 1

image:
  repository: dattruongquoc/app
  tag: 5f1e63cb3687a6c9b09242f82045fb5334e1de65
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "*"   # hoặc "*" để wildcard
      paths:
        - path: /app
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  namespace: api

tolerations:
  - key: "namespace"
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"
#change triger helm release